  development[m
  feat/banner-add-edit[m
  feat/restaurant-details-edit[m
  feat/restaurant-details-page[m
  feat/restaurant-details-sidebar[m
  feat/restaurant-status-ui[m
  feat/user-homepage[m
* [32mfeat/wishlist[m
  feature/auth[m
  feature/forgot-password[m
  feature/image-cropping[m
  feature/onboarding[m
  feature/restaurant-menu-management[m
  feature/restaurant-pre-approval[m
  feature/user-profile[m
  feature/user-suspension-redis[m
  fix/onboarding-approve-visibility[m
  fix/restaurant-sidebar[m
  main[m
  week1/login[m
  week1/register[m
